import Sidebar from "@/components/admin/Sidebar"
import "../globals.css";
import Header from "@/components/admin/Header";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-indigo-100/75">
        <main className="flex bg-black">
          <Sidebar/>
          <div className="flex flex-col bg-blue-400 p-4 w-full max-h-50">
            <Header/>
            {children}
          </div>
        </main>
      </body>
    </html>
  )
}
